Update CI-CD.yaml

diff --git a/.github/workflows/CI-CD.yaml b/.github/workflows/CI-CD.yaml
--- a/.github/workflows/CI-CD.yaml
+++ b/.github/workflows/CI-CD.yaml
@@ -33,7 +33,7 @@ jobs:
   build-and-push:
     name: Build & Push Docker Image
     runs-on: ubuntu-latest
-    #needs: validate-yaml
+    needs: validate-yaml
 
     steps:
       - uses: actions/checkout@v3
@@ -45,6 +45,19 @@ jobs:
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: ${{ env.AWS_REGION }}
 
+      # Install Docker on EC2 instance
+      - name: Install Docker if not present
+        if: steps.app_check.outputs.changed_files != ''
+        run: |
+          if ! command -v docker &> /dev/null; then
+            echo "Docker not found. Installing..."
+            sudo apt update
+            sudo apt install -y docker.io
+            sudo systemctl start docker
+          else
+            echo "Docker already installed."
+          fi
+          
       - name: Docker Login
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
 
